# Generated by Django 5.0.7 on 2024-07-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Snack', 'Snack')], max_length=50)),
            ],
        ),
    ]
